spring.application.name=expense-tracker-api
server.port=8080

# Return clean field name (not "date") formatting for LocalDate as ISO-8601 (yyyy-MM-dd)
spring.jackson.date-format=yyyy-MM-dd
spring.jackson.serialization.write-dates-as-timestamps=false
